### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by mtalhagaoglu** [perrystreetsoftware/react-native-rtmpview#17]
i am publish an rtmp stream and i can watch this on vlc or other rtmp players but i have an issue in this module. it sometimes shows, sometimes doesn't. it isn't stabil. sometimes it shows but when i do quick look another app comes back it doesnt show more. please help me about that. thank you.

**Comment by mtalhagaoglu** [comment]
I was using this module in my react-native android project and it wasn't so
great. Like I said it wasn't stabil. So I am using another module right
now. And it is very useful to me. I can't remember it's name now but it's
like node something...

And I wasn't get any error message it's just cut the stream and show me
black screen

**Comment by Epothos333** [comment]
Without additional information, we have no recommendations at this time, but it sounds like it could be an issue with your stream or connection.
