### ISSUE TITLE
Can not play a rtsp URL on Android

### ISSUE THREAD

**Issue by nhiicts** [perrystreetsoftware/react-native-rtmpview#18]
Please give me some advices for the bug when running rtsp url on Android
```
"error": "com.google.android.exoplayer2.ExoPlaybackException: net.butterflytv.rtmp_client.RtmpClient$RtmpIOException: RTMP error: -12"
```
react-native: 0.61
```
ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 17
        compileSdkVersion = 28
        targetSdkVersion = 28
        exoPlayerVersion = "2.10.5"
    }
```

**Comment by esilverberg** [comment]
This looks like an exoplayer issue -- 

https://github.com/ant-media/LibRtmp-Client-for-Android/issues/65

You could try using a new or different version of ExoPlayer with this library.

**Comment by nhiicts** [comment]
@esilverberg Thanks for your answer. I've tried latest version of ExoPlayer which is `2.10.5`, but it seem doesn't work.

**Comment by esilverberg** [comment]
What about an older version of ExoPlayer?

**Comment by nhiicts** [comment]
@esilverberg I've tried several versions from `2.9.6` to `2.10.5`, but it seems doesn't work

**Comment by nhiicts** [comment]
@esilverberg I found that it works for normal RTSP link like `rtmp://fms.105.net/live/rmc1`. But it is not works with url like `rtsp://admin:admin@xxx.xxx`.

**Comment by esilverberg** [comment]
https://github.com/google/ExoPlayer/issues/55
