### ISSUE TITLE
When library available for Android?

### ISSUE THREAD

**Issue by anhtuank7c** [perrystreetsoftware/react-native-rtmpview#2]
A question as title describe

**Comment by esilverberg** [comment]
We are planning on getting to work on this later this fall!

**Comment by pribeh** [comment]
Sorry to ask the dumb question again, but are you any closer to picking a library to work with on the android side?

**Comment by anhtuank7c** [comment]
@pribeh This one work very well https://github.com/react-native-vietnam/react-native-nodemediaclient

**Comment by esilverberg** [comment]
We now support Android - see our [README.md](https://github.com/perrystreetsoftware/react-native-rtmpview/blob/master/README.md) for comments about the thinking behind the library we elected to integrate and support on that platform, [ExoPlayer](https://github.com/google/ExoPlayer).
